### ISSUE TITLE
Dokumentation + Överlämning

### ISSUE THREAD

**Issue by Karlkorv** [acoustic-warfare/beamforming-lk#99]
Denna kommer bli rätt maffig och vi får nog prioritera lite kring vad som är viktigast:

In no particular ordning:

- Boot-instruktioner: du har en helt blank dator, hur tankar du ner och startar ljudkriget? Hur testar du med FPGA:s eller med udpreplay-filer?
- Utvecklingsinstruktioner: Vart börjar man för att göra modifikationer? Vart hittar man info kring vad saker gör och hur vet man vad som är kritiskt eller ej?
- Further reading: Vart lär man sig allt vi har lärt oss? Två månader är rätt mycket tid att dunka in massa info i ens huvud, att dela med sig av så många av dessa externa informationskällor som möjligt känns vettigt
- CMAKE: ?????
- WIKI/Doxygen: Om möjligt?

**Comment by Karlkorv** [comment]
# ¡Viktigt!
Lämna .pcap-filerna någonstans där de går att hitta!!

**Comment by tuvabjornberg** [comment]
Wikis påbörjade
